/** Fictional aphorisms. Not contractual guidance. */
export const CONTRACT_WISDOM = [
  "Ein Vertrag ist erst übersichtlich, wenn man auch die Fußnoten ohne Lupe versteht.",
  "Wer den Anhang kennt, wundert sich seltener über den Hauptteil.",
  "Die kürzeste Vertragsklausel ist nicht immer der kürzeste Weg zur Antwort.",
  "Eine gute Frage spart mehr Zeit als drei ungezielte Suchläufe.",
  "Wenn zwei Versionen „final“ heißen, beginnt die Archäologie.",
  "Manche Vertragsklauseln brauchen keine Auslegung, sondern eine Landkarte.",
  "Der kleinste Stern im Dokument zeigt manchmal auf den längsten Absatz.",
  "Eine saubere Quelle ist besser als zehn gut gemeinte Vermutungen.",
  "Wer den Geltungsbereich übersieht, bekommt eine sehr weit gereiste Antwort.",
  "Fristen sind wie Geburtstage: Wer sie notiert, hat weniger Überraschungen.",
  "Ein Nachtrag kommt selten allein, aber meistens ohne Blumen.",
  "Die Wahrheit steht manchmal im Vertrag und manchmal in Anlage zwölf.",
  "Wer eine Ausnahme findet, sollte auch die Regel im Auge behalten.",
  "Im Vertragswesen ist „kurz“ oft nur die Abkürzung für „siehe Anlage“.",
  "Ein guter Filter ersetzt keine gute Frage, aber viele Klicks.",
  "Die Vertragsversion von gestern ist heute schon ein Zeitzeuge.",
  "Ein eindeutiger Status ist ein kleiner Urlaub für das Gehirn.",
  "Was nicht dokumentiert ist, hat zumindest ein ernstes Gedächtnisproblem.",
  "Manche Begriffe sind so dehnbar, dass sie als Theraband durchgehen.",
  "Die eleganteste Antwort ist oft die mit einer überprüfbaren Quelle.",
  "Ein Änderungsprotokoll ist das Tagebuch eines Vertrages ohne Liebesgeschichte.",
  "Vertrauen ist gut, ein lesbarer Seitenverweis ist entspannter.",
  "Ein Datensatz ohne Herkunft ist wie ein Besen ohne Stiel.",
  "Eine Vertragsmatrix bringt Ordnung in Dinge, die vorher nebeneinander herflogen.",
  "Wer nur nach dem Preis fragt, bekommt manchmal die halbe Geschichte.",
  "Jeder Nachtrag ist ein Hinweis darauf, dass auch Verträge dazulernen.",
  "Der beste Suchbegriff ist der, der im richtigen Dokument landet.",
  "Eine sauber formulierte Rückfrage ist keine Schwäche, sondern Navigation.",
  "Bei langen Verträgen gewinnt nicht der schnellste Leser, sondern der sorgfältigste.",
  "Wenn die Versionsnummer steigt, sollte auch die Aufmerksamkeit steigen.",
  "Die Fußnote ist klein, aber ihr Selbstbewusstsein ist groß.",
  "Ein Gültigkeitsdatum ist kein Deko-Element für Tabellen.",
  "Man kann vieles abkürzen, nur nicht die Prüfung des Kontextes.",
  "Der Vertrag hat immer Recht auf einen zweiten Blick, aber nicht automatisch in der Sache.",
  "Wer doppelte Daten pflegt, verdoppelt irgendwann die Fragen.",
  "Ein gutes Formular stellt die Fragen, bevor sie entstehen.",
  "Manche Unterlagen sind so gut versteckt, dass sie eine eigene Postleitzahl verdienen.",
  "Ordnung ist, wenn die Quelle schneller gefunden wird als der Kaffee kalt wird.",
  "„Das war schon immer so“ ist keine Versionsnummer.",
  "Ein klarer Geltungsbereich ist der Sicherheitsgurt der Vertragsauskunft.",
  "Die beste Datei heißt nicht „neu“, sondern trägt ein nachvollziehbares Datum.",
  "Was heute eine Randnotiz ist, kann morgen ein Hauptthema sein.",
  "Ein Vertrag ohne Zuständigkeit ist wie ein Besen ohne Richtung.",
  "Fragen kosten Zeit; unbeantwortete Fragen kosten oft mehr.",
  "Wer Abkürzungen sammelt, braucht irgendwann ein eigenes Wörterbuch.",
  "Keine Ampel ersetzt den Blick auf die Kreuzung.",
  "Ein grüner Status fühlt sich gut an; die Begründung macht ihn wertvoll.",
  "Die schnellste Freigabe ist nicht immer die beste Abkürzung.",
  "Wenn etwas „selbsterklärend“ heißt, wartet meist noch eine Erklärung.",
  "Ein gültiger Vertrag ist noch keine vollständige Fallprüfung.",
  "Es gibt keine kleinen Anhänge, nur unterschätzte.",
  "Der beste Arbeitsvorrat ist der, dessen Priorität man versteht.",
  "Ein Datum ohne Zeitbezug ist ein Kalenderblatt auf Reisen.",
  "Manchmal ist das wichtigste Wort im Vertrag ein unscheinbares „außer“.",
  "Gute Datenpflege ist unsichtbar, bis sie einmal fehlt.",
  "Wer die Herkunft kennt, findet bei Unklarheiten schneller zurück.",
  "Eine offene Frage ist besser als eine geschlossene Vermutung.",
  "Ein Querverweis ist nur hilfreich, wenn er nicht ins Nirgendwo zeigt.",
  "Die Stärke einer Wissensdatenbank erkennt man an ihren belegten Antworten.",
  "Wissen wächst, wenn Entscheidungen nachvollziehbar werden.",
  "Ein klarer Prozess spart nicht jede Frage, aber viele Umwege.",
  "Wo „ggf.“ steht, sollte die Aufmerksamkeit aufrecht sitzen.",
  "Eine Tabelle ohne Überschrift ist ein Rätsel mit Zahlen.",
  "Gute Standards erleichtern den Alltag; gute Ausnahmen erklären die Abweichung.",
  "Wer Unterschiede zwischen Kassen erkennt, spart später Verwechslungen.",
  "Die Vertragsnummer ist weniger poetisch als der Titel, aber oft eindeutiger.",
  "„Aktuell“ ist ein schönes Wort, wenn ein Datum danebensteht.",
  "Ein sauberer Import ist der erste freundliche Händedruck der Daten.",
  "Die fehlende Anlage hat meistens den größten Auftritt.",
  "Ein Prüfvermerk ohne Ergebnis ist ein Krimi ohne Auflösung.",
  "Die beste Regel kann nur helfen, wenn sie gefunden wird.",
  "Versionierung macht Änderungen sichtbar, bevor sie zu Legenden werden.",
  "Ein gutes Änderungsprotokoll beantwortet auch die Frage „Warum?“.",
  "Wer zwei ähnliche Positionen sieht, sollte den Unterschied nicht weglächeln.",
  "Fachwissen und Humor vertragen sich gut; nur die Rollen sollten klar bleiben.",
  "Ein systematischer Vergleich ist wie Aufräumen mit eingebauter Taschenlampe.",
  "Nicht jede Lücke ist ein Fehler; manche sind eine ehrliche offene Frage.",
  "Der schönste Vertragsauszug nützt wenig ohne den richtigen Geltungsbereich.",
  "Manche Diskussionen werden kürzer, sobald jemand die Originalquelle öffnet.",
  "Eine Prüfqueue ist keine Schande, sondern die Warteschlange der Klarheit.",
  "Der erste Schritt zur richtigen Antwort ist ein sauberer Ausgangspunkt.",
  "Ein gutes Feldlabel ersetzt fünf Minuten Rätselraten.",
  "Bei Vertragsdaten zählt nicht die Lautstärke, sondern die Nachvollziehbarkeit.",
  "Wer die Ausnahme erklärt, macht die Regel erst verständlich.",
  "Die perfekte Suche ist die, bei der man nicht weiß, wie viel Arbeit sie spart.",
  "Dokumentation ist das Gedächtnis einer Organisation mit besserer Suchfunktion.",
  "Ein vorsichtiges „noch zu prüfen“ ist manchmal die professionellste Antwort.",
  "Die Anzahl der Klicks sagt wenig über die Qualität der Entscheidung.",
  "Eine klare Zuständigkeit ist eine kleine Zauberformel im Arbeitsalltag.",
  "Nicht jeder Nachtrag ändert alles; aber jeder verdient einen Blick.",
  "Ein gutes Dashboard zeigt nicht nur Zahlen, sondern die offenen Fragen dahinter.",
  "Wer aus Freitext Struktur macht, spart dem nächsten Kollegen eine Schatzsuche.",
  "Eine eindeutige Positionszuordnung ist mehr wert als ein schöner Dateiname.",
  "Ohne Originalquelle wird auch die beste Vermutung nicht amtlich.",
  "Der richtige Zeitpunkt für eine Rückfrage ist vor der voreiligen Antwort.",
  "Manchmal ist weniger Information mehr Übersicht – wenn das Wesentliche bleibt.",
  "Ein guter Vertragsexperte hat nicht jede Antwort im Kopf, aber jeden Prüfweg im Blick.",
  "Die ideale Checkliste merkt auch, wenn eine Voraussetzung noch ungeklärt ist.",
  "Ein verständlicher Hinweis ist besser als ein mysteriöses Warnsymbol.",
  "Der schönste Feierabend beginnt mit einer leeren Liste offener Überraschungen."
]
