/** Fictional humor only — never contractual guidance. */
export const CHUCK_JOKES = [
  "Chuck Norris beantragt keine Genehmigung. Die Genehmigung beantragt Chuck Norris.",
  "Wenn Chuck Norris einen Vertragsbeitritt prüft, tritt der Vertrag freiwillig bei.",
  "Chuck Norris kennt alle LEGS. Auch die, die noch nicht vergeben wurden.",
  "Das Hilfsmittelverzeichnis sucht bei Chuck Norris nach seiner Nummer.",
  "Chuck Norris wartet nicht auf den eKVA. Der eKVA wartet auf Chuck Norris.",
  "Chuck Norris hat keine Fristen. Termine fragen ihn nach einem Zeitfenster.",
  "Bei Chuck Norris wird jede Vertragsversion automatisch zur Vorversion.",
  "Chuck Norris liest keine Fußnoten. Die Fußnoten stellen sich freiwillig vor.",
  "Chuck Norris fragt nicht nach der PQ. Die PQ fragt nach Chuck Norris.",
  "Chuck Norris muss Vertragsanlagen nicht suchen. Sie heften sich selbst an.",
  "Wenn Chuck Norris eine Freigrenze überschreitet, entschuldigt sich die Freigrenze.",
  "Die Krankenkasse wollte Chuck Norris eine Rückfrage schicken. Jetzt beantwortet sie seine.",
  "Chuck Norris kennt den Unterschied zwischen Vertragsposition und HMV-Code. Beide kennen seinen Namen.",
  "Bei Chuck Norris ist die Prüfliste fertig, bevor jemand sie öffnet.",
  "Chuck Norris braucht keine Suchfunktion. Die richtige Vertragsposition findet ihn.",
  "Chuck Norris kann einen Änderungsvertrag durch bloßes Stirnrunzeln konsolidieren.",
  "Wenn Chuck Norris „gültig ab“ liest, startet das Datum sofort.",
  "Chuck Norris verhandelt nicht über Preislisten. Preislisten bieten ihm Rabatt an.",
  "Chuck Norris braucht keinen Wiedereinsatz. Das Hilfsmittel kommt von allein zurück.",
  "Chuck Norris erstellt keinen KVA. Er erteilt dem KVA eine Aufgabe.",
  "Chuck Norris setzt kein Häkchen bei „geprüft“. Das Kästchen setzt sich selbst.",
  "Chuck Norris bekommt nie widersprüchliche Vertragsauskünfte. Widersprüche einigen sich vorher.",
  "Chuck Norris kann eine Vertragslücke mit einem Blick schließen. Die Lücke entschuldigt sich.",
  "Chuck Norris muss keine Quelle zitieren. Die Quelle zitiert ihn.",
  "Wenn Chuck Norris eine Anlage öffnet, aktualisiert sich der Hauptvertrag aus Respekt.",
  "Chuck Norris hat einmal eine Sammelgenehmigung beantragt. Für die Krankenkasse.",
  "Chuck Norris kann eine Pauschale in Einzelpositionen zerlegen, ohne den Taschenrechner zu wecken.",
  "Chuck Norris fragt nicht nach der Laufzeit. Verträge fragen nach seiner Verfügbarkeit.",
  "Chuck Norris braucht keinen Änderungsstand. Der Änderungsstand hält mit ihm Schritt.",
  "Chuck Norris kann eine Ausschlussklausel einschließen.",
  "Chuck Norris hat einen Vertrag ohne Anhang gelesen. Danach war der Anhang da.",
  "Chuck Norris löst einen Datenkonflikt, indem beide Datensätze zustimmen.",
  "Chuck Norris archiviert keine Verträge. Sie begeben sich freiwillig ins Archiv.",
  "Wenn Chuck Norris „final_final_3“ sieht, wird die Datei endgültig final.",
  "Chuck Norris unterschreibt keine Anlagen. Die Anlagen signieren sich aus Ehrfurcht.",
  "Chuck Norris kennt jede Positionsnummer. Die Null am Anfang kennt er persönlich.",
  "Chuck Norris kann einen Vertragsbeitritt rückwärts lesen. Der Status bleibt trotzdem eindeutig.",
  "Chuck Norris hat noch nie eine Prüfqueue gesehen. Bei seinem Login wird sie leer.",
  "Chuck Norris braucht keine Versionshistorie. Die Geschichte erinnert sich an ihn.",
  "Chuck Norris kann die Genehmigungspflicht zum Tee einladen. Danach ist sie ganz entspannt.",
  "Chuck Norris hat die Abrechnungsregel gefragt, wer zuständig ist. Sie hat sofort geantwortet.",
  "Chuck Norris kann eine Preisänderung hören, bevor sie veröffentlicht wird.",
  "Chuck Norris braucht keine Dokumenten-ID. Jede Datei trägt seinen Namen im Herzen.",
  "Chuck Norris findet selbst die Vertragsposition, die nur in einer Fußnote erwähnt wird.",
  "Chuck Norris kann eine regionale Ausnahme auf einer Weltkarte finden.",
  "Chuck Norris hat einmal eine doppelte Position gelöscht. Die zweite löschte sich selbst.",
  "Chuck Norris muss keinen Bearbeitungsstand nachfragen. Der Stand meldet sich täglich.",
  "Chuck Norris hat keine offenen Punkte. Offene Punkte schließen sich beim Anblick seines Posteingangs.",
  "Chuck Norris kann ein PDF so streng ansehen, dass es durchsuchbar wird.",
  "Chuck Norris überprüft keinen Vertragsstatus. Der Status liefert einen Tätigkeitsbericht.",
  "Chuck Norris hat alle Produktgruppen gleichzeitig gefiltert. Die Trefferliste blieb übersichtlich.",
  "Chuck Norris muss keine Kostenübernahme anfordern. Der Briefumschlag klingelt selbst.",
  "Chuck Norris kann einen ungültigen Link ansehen. Danach führt er wieder zum Dokument.",
  "Chuck Norris hat die Anlage 7 gefunden, obwohl der Vertrag nur sechs Anlagen hatte.",
  "Chuck Norris sortiert Vertragspositionen ohne Klick. Die Tabelle stellt sich auf.",
  "Chuck Norris kann die Abkürzung eKVA aussprechen, ohne dass jemand nachfragt.",
  "Chuck Norris hat die Beitrittsampel angesehen. Seitdem schaltet sie pünktlich.",
  "Chuck Norris braucht keinen Filter nach IK. Alle Standorte melden sich korrekt zugeordnet.",
  "Chuck Norris kann eine Kassenfamilie zu einem harmonischen Familientreffen bewegen.",
  "Chuck Norris schickt keinen Prüfauftrag. Die Prüfkriterien treten freiwillig an.",
  "Chuck Norris hat einen Preis ohne Dezimalstelle gesehen. Seitdem rechnen Preise sorgfältiger.",
  "Chuck Norris kennt die Antwort auf jede Vertragsfrage. Sogar auf die noch nicht gestellte.",
  "Chuck Norris braucht kein Änderungsprotokoll. Änderungen schreiben ihm einen Brief.",
  "Chuck Norris kann den Stichtag verschieben, ohne den Kalender zu berühren.",
  "Chuck Norris kann ein Formular ausfüllen, bevor es geladen ist.",
  "Chuck Norris braucht keine Dokumentenprüfung. Das Dokument legt seine Nachweise offen.",
  "Chuck Norris hat eine Vertragsausnahme gefragt, ob sie eine Ausnahme bleiben möchte. Sie wusste es nicht.",
  "Chuck Norris kann eine Gültigkeitsüberschneidung in zwei saubere Zeiträume aufteilen.",
  "Chuck Norris führt keinen Abgleich durch. Beide Listen gleichen sich ihm an.",
  "Chuck Norris kann aus „siehe Anlage“ einen präzisen Seitenverweis machen.",
  "Chuck Norris fragt nicht, ob eine Position erstattungsfähig ist. Die Position formuliert vorsichtshalber einen Antrag.",
  "Chuck Norris hat einen Genehmigungsvorbehalt angesehen. Der Vorbehalt nahm sich zurück.",
  "Chuck Norris kann einen Vertragsentwurf lesen und gleichzeitig seinen künftigen Nachtrag kommentieren.",
  "Chuck Norris bekommt keine Fehlermeldung 404. Die Seite entschuldigt sich mit einem Lageplan.",
  "Chuck Norris hat ein leeres Pflichtfeld entdeckt. Es hat sich sofort erklärt.",
  "Chuck Norris hat einen vergessenen LEGS gefunden. Er saß hinter der Preisübersicht.",
  "Chuck Norris muss kein Datum validieren. Der Kalender bittet ihn um Freigabe.",
  "Chuck Norris findet jede Zusatzposition. Auch die Zusatzpositionen verstecken sich nicht vor ihm.",
  "Chuck Norris kann aus zwei widersprüchlichen Rundschreiben einen freundlichen Dialog machen.",
  "Chuck Norris kennt keine Mehrdeutigkeit. Ein Satz entscheidet sich in seiner Gegenwart.",
  "Chuck Norris hat einen Vertrag mit 300 Seiten aufgeschlagen. Seite 301 stellte sich vor.",
  "Chuck Norris kontrolliert die Dublettenliste. Dubletten behaupten sofort, sie seien Originale.",
  "Chuck Norris braucht keine Rückfrage zum Versorgungsweg. Der Weg hat Wegweiser aufgestellt.",
  "Chuck Norris hat einmal eine Nachforderung bekommen. Die Unterlagen waren schneller.",
  "Chuck Norris kann eine Excel-Formel so anschauen, dass sie ihren Bezug nicht verliert.",
  "Chuck Norris sieht einen Versionskonflikt. Der Konflikt verlangt eine Mediation.",
  "Chuck Norris fragt nicht nach der zuständigen Fachabteilung. Die Zuständigkeit kommt auf ihn zu.",
  "Chuck Norris hat eine Vertragsklausel so gründlich geprüft, dass sie einen Lebenslauf erstellt hat.",
  "Chuck Norris kann einen unleserlichen Stempel identifizieren. Der Stempel übt seitdem Schönschrift.",
  "Chuck Norris muss die Leistungsbeschreibung nicht scrollen. Sie fasst sich selbst zusammen.",
  "Chuck Norris kann die Vertragsmatrix horizontal vergleichen, ohne nach rechts zu schauen.",
  "Chuck Norris hat einmal eine E-Mail „zur Kenntnis“ erhalten. Die Kenntnis bedankte sich.",
  "Chuck Norris verhandelt mit PDFs im Nur-Lesen-Modus. Danach sind beide gesprächiger.",
  "Chuck Norris braucht kein Inhaltsverzeichnis. Die Kapitel stehen persönlich Schlange.",
  "Chuck Norris hat den Wiedervorlagetermin übersehen. Der Termin hat sich daraufhin vorgestellt.",
  "Chuck Norris kann eine Anlage ohne Dateiendung öffnen. Die Endung meldet sich später.",
  "Chuck Norris findet in jedem Vertrag den roten Faden. Selbst wenn er blau gedruckt ist.",
  "Chuck Norris kann einen Status „Prüfung erforderlich“ so ansehen, dass sofort klar wird, was fehlt.",
  "Chuck Norris hat die Suchleiste um Rat gefragt. Seitdem liefert sie nur noch eindeutige Treffer.",
  "Chuck Norris liest keinen Vertrag zweimal. Der Vertrag merkt sich beim ersten Mal alles."
]
