/** Fictional payer & approval jokes; no legal or business assertions. */
export const PAYER_JOKES = [
  "Die Genehmigung kam schneller als erwartet. Jetzt prüft das Büro, ob es wirklich Montag ist.",
  "Die Krankenkasse fragte nach einer Anlage. Der Drucker fragte nach Urlaub.",
  "Ein eKVA ging spazieren und kam mit drei Rückfragen zurück.",
  "Die Freigrenze wollte hoch hinaus. Die Vertragsanlage bat um Bodenhaftung.",
  "Eine Kostenübernahme ist wie ein grüner Haken: Man freut sich, aber schaut lieber genau hin.",
  "Die Rückfrage hatte eine Rückfrage. Beide wurden an die Fachabteilung weitergeleitet.",
  "Im Kassenvergleich herrscht Harmonie – bis jemand nach der Zusatzposition fragt.",
  "Eine Genehmigungspflicht und eine Ausnahme treffen sich. Beide sagen: „Kommt auf den Vertrag an.“",
  "Der Antrag war vollständig. Das System fragte vorsichtshalber nach Vollständigkeit.",
  "Manche Freigrenzen sind schüchterner als eine unbeschriftete Excel-Spalte.",
  "Die Krankenkasse wollte einen Nachweis. Der Nachweis suchte seine Quelle.",
  "Die Verordnung und der KVA diskutierten. Die Dokumentation schrieb mit.",
  "„Einheitliche Regelung“ ist oft der Beginn einer regionalen Entdeckungsreise.",
  "Eine Genehmigungsampel ging zum Optiker. Seitdem sieht sie mehr Gelb.",
  "Der eKVA hat kein Lampenfieber. Aber manchmal Ladehemmungen.",
  "Die Vertragsanlage sagte „genehmigungsfrei“. Der Einzelfall fragte: „Für wen?“",
  "Zwischen Antrag und Antwort liegt manchmal nur ein kleiner Stapel Papier. Manchmal ein Gebirge.",
  "Der Kostenträger fragte nach der Positionsnummer. Die Position fragte nach dem Kostenträger.",
  "Eine Rückmeldung kam ohne Kontext. Jetzt führt sie ein Schattendasein in der Inbox.",
  "Im Vertragsdschungel hilft ein guter Kompass. Und eine zuverlässige Suchfunktion.",
  "Der Bescheid war so knapp, dass sogar die Satzzeichen nach einer Erläuterung fragten.",
  "Die Vertragsregel wechselte die Farbe. Die Ampel beantragte eine Schulung.",
  "Eine regionale Besonderheit war auf Weltreise. Die Zuordnung bat um Rückkehr.",
  "Der KVA wollte nur kurz raus. Danach hatte er eine neue Vorgangsnummer.",
  "Krankenkassen haben unterschiedliche Regeln. Die Tabellenkalkulation hat dazu eine Meinung.",
  "Das Zusatzformular kam als Überraschungsgast. Niemand hatte einen Stuhl vorbereitet.",
  "Die Versorgungsanzeige meldete sich selbst an. Wenigstens einer wusste Bescheid.",
  "Der Antrag bekam einen Stempel. Er fühlte sich plötzlich sehr offiziell.",
  "Die Genehmigung wurde gefragt, ob sie heute erscheint. Sie verwies auf den Bearbeitungsstand.",
  "Die Positionsbeschreibung war so präzise, dass der Rückfragenordner kurz leer wurde.",
  "Bei einer Kassenauskunft gilt manchmal: Erst der Geltungsbereich, dann das große Aufatmen.",
  "Die Leistungsbeschreibung kam mit Zusatzbedingungen. Sie nannte sie „kleines Gepäck“.",
  "Ein Rundschreiben und ein Nachtrag waren uneins. Das Änderungsprotokoll musste vermitteln.",
  "Die Abrechnungsposition stand auf der Gästeliste. Die Zusatzposition wollte mitkommen.",
  "Der Versorgungszeitraum hatte es eilig. Die Fristenverwaltung blieb erstaunlich gelassen.",
  "Eine Kasse sagte „Standard“. Die nächste sagte „Sonderfall“. Die Matrix holte tief Luft.",
  "Die Wiedereinsatzregel wollte Recycling fördern. Der Aktenordner fühlte sich angesprochen.",
  "Eine Preisposition suchte Anschluss. Der Vertragsbeitritt fragte nach dem Ausweis.",
  "Die Fachabteilung sagte „prüfen“. Die Ampel sagte „gelb“. Alle waren sich ausnahmsweise einig.",
  "Ein Formular meldete sich als Pflicht. Die Quelle fragte höflich nach dem Beleg.",
  "Die Genehmigung war in Bearbeitung. Die Kaffeemaschine auch.",
  "Eine Anlage versteckte sich hinter einem Link. Der Link behauptete, er sei nicht zuständig.",
  "Ein Kostenträgerwechsel ist kein Staffellauf, aber eine saubere Übergabe hilft.",
  "Die Kassenregel schickte ein Update. Die alte Version bat um einen Abschiedsbrief.",
  "Der KVA hatte fünf Felder. Vier waren klar, das fünfte wollte eine Sitzung.",
  "Die Verordnung wollte sich kurz vorstellen. Der Vertrag verlangte den vollständigen Namen.",
  "Ein Genehmigungsstatus ist keine Wettervorhersage, aber Gelb heißt oft: Schirm mitnehmen.",
  "Die Sondervereinbarung betrat den Raum. Alle Standardprozesse rückten ein Stück zusammen.",
  "Der Kostenträger rief an. Der Vertragsordner tat so, als wäre er schon sortiert.",
  "Die Bearbeitungsfrist trug Turnschuhe. Das Postfach blieb auf seinem Stuhl sitzen."
]
