/** Fictional light-hearted office wisdom. */
export const OFFICE_WISDOM = [
  "Der Montag ist kein Fehler im Kalender, sondern ein besonders langer Ladebalken.",
  "Eine gute Ablage ist der Ort, an dem man auch freitags um 16 Uhr etwas wiederfindet.",
  "Wer einen Termin zusagt, sollte ihm auch einen Platz im Kalender anbieten.",
  "Kaffee löst keine Vertragsfrage, aber er macht den Weg zur Antwort geselliger.",
  "Eine Rückfrage ist schneller erledigt, wenn sie eine konkrete Frage enthält.",
  "Der Posteingang schläft nie. Die Mitarbeitenden sollten es trotzdem tun.",
  "Ein sauberer Dateiname ist eine kleine Aufmerksamkeit für das zukünftige Ich.",
  "„Ich habe es dir geschickt“ und „Du hast es gefunden“ sind zwei verschiedene Ereignisse.",
  "Eine Besprechung braucht ein Ziel, nicht nur einen freien Konferenzraum.",
  "Wer seine Prioritäten kennt, lässt sich nicht von jedem roten Ausrufezeichen beeindrucken.",
  "Eine Checkliste ist die freundlichste Form des Erinnerns.",
  "Die beste Notiz beantwortet auch Wochen später noch die Frage „Was war gemeint?“.",
  "Ein guter Übergabevermerk erspart dem nächsten Team die Detektivarbeit.",
  "Die Ablage sollte nicht nur den Menschen verstehen, der sie angelegt hat.",
  "Ein offener Vorgang wird nicht leichter, wenn man ihn umbenennt.",
  "Wer Pausen plant, muss sie seltener zwischen zwei Fehlermeldungen suchen.",
  "Das gemeinsame Laufwerk ist kein Dachboden, auch wenn es manchmal so aussieht.",
  "Eine Aufgabe ohne Verantwortliche ist eine Einladung zum Versteckspiel.",
  "Die richtige Reihenfolge spart mehr Zeit als hektische Geschwindigkeit.",
  "Wer einen Fehler offen anspricht, macht daraus vielleicht eine Verbesserung.",
  "Ein gutes Formular sammelt Antworten, nicht Rätsel.",
  "Der schnellste Klick führt nicht immer zum richtigen Fenster.",
  "Eine verständliche Überschrift ist ein Service an alle, die gerade fünf Tabs offen haben.",
  "„Dringend“ wird glaubwürdiger, wenn ein Termin danebensteht.",
  "Die schönste E-Mail ist die, bei der der Betreff zum Inhalt passt.",
  "Eine Entscheidung ohne Protokoll ist eine Geschichte mit vielen Erzählern.",
  "Wer den letzten Stand teilt, muss die Vorgeschichte seltener erzählen.",
  "Ein klarer Arbeitsauftrag ist der Anfang einer entspannten Zusammenarbeit.",
  "Ordnung entsteht nicht durch mehr Ordner, sondern durch verständliche Zuordnung.",
  "Die beste Erinnerung ist die, die vor der Frist auftaucht.",
  "Eine Suchfunktion weiß viel, aber nicht immer, was man eigentlich meint.",
  "Ein gutes Team fragt nach, bevor aus einer Annahme ein Prozess wird.",
  "Fehlermeldungen sind keine Liebesbriefe, aber man sollte sie trotzdem lesen.",
  "Ein ruhiger Bildschirm macht die Aufgabe nicht kleiner, aber oft klarer.",
  "Wer eine Datei „endgültig“ nennt, sollte sehr optimistisch sein.",
  "Ein Statusbericht darf kurz sein, wenn er das Wichtige nicht vergisst.",
  "Mehr Schaltflächen bedeuten nicht automatisch mehr Möglichkeiten.",
  "Eine sinnvolle Automatisierung lässt Menschen mehr Zeit für schwierige Fälle.",
  "Die perfekte Übergabe braucht weder Rätsel noch Zauberei.",
  "Wer die Suchmaske vereinfacht, schenkt allen ein paar Sekunden zurück.",
  "Manche Prozesse sind gewachsen. Ab und zu brauchen sie einen Schnitt.",
  "Ein sauber dokumentiertes „Nein“ hilft mehr als ein unverständliches „Vielleicht“.",
  "Eine gute Rückmeldung nennt nicht nur das Problem, sondern möglichst auch den Ort.",
  "Das Betriebshandbuch ist am nützlichsten, wenn es nicht nur bei Audits geöffnet wird.",
  "Ein freier Nachmittag beginnt manchmal mit einem sauber abgeschlossenen Vorgang.",
  "Ein Team wird nicht besser durch weniger Fragen, sondern durch bessere Antworten.",
  "Es gibt einen Unterschied zwischen „gelesen“ und „verstanden“ – besonders bei Rundmails.",
  "Ein Button ohne Funktion ist wie eine Tür ohne Raum dahinter.",
  "Wer Feedback ernst nimmt, erspart sich manche zweite Version.",
  "Der eleganteste Arbeitstag endet ohne ungeklärte Zuständigkeiten."
]
